### ISSUE TITLE
null-safety 지원여부

### ISSUE THREAD

**Issue by bluey2ks** [LBSTECH/naver_map_plugin#40]
null-safety 지원여부 관련 업데이트 사항 있나요?

**Comment by youngminz** [comment]
아직 릴리즈 되지 않은 master 최신 코드인 0.9.7 버전에서 null-safety 지원하는 거 같습니다. 아래와 같이 적용하시면 null-safety 적용 되네요.
```
dependencies:
  naver_map_plugin:
    git:
      url: git://github.com/LBSTECH/naver_map_plugin.git
      ref: 9aa02b575391a59d8db314a9af76d5d803ccd8c8
```
